macro(WRAP_CPP outfiles)
	# get include dirs
	QT4_GET_MOC_FLAGS(moc_flags)
	QT4_EXTRACT_OPTIONS(moc_files moc_options ${ARGN})

	foreach(it ${moc_files})
		get_filename_component(_abs_FILE ${it} ABSOLUTE)
		get_filename_component(_abs_PATH ${_abs_FILE} PATH)
		get_filename_component(_basename ${it} NAME_WE)

		set(_HAS_MOC false)

		if(EXISTS ${_abs_PATH}/${_basename}.cpp)
			set(_header ${_abs_PATH}/${_basename}.cpp)
			file(READ ${_header} _contents)
			string(REGEX MATCHALL "# *include +[^ ]+\\.moc[\">]" _match "${_contents}")
			if(_match)
				set(_HAS_MOC true)
				foreach(_current_MOC_INC ${_match})
					string(REGEX MATCH "[^ <\"]+\\.moc" _current_MOC "${_current_MOC_INC}")
					set(_moc    ${CMAKE_CURRENT_BINARY_DIR}/${_current_MOC})
					QT4_CREATE_MOC_COMMAND(${_abs_FILE} ${_moc} "${_moc_INCS}" "")
					macro_add_file_dependencies(${_abs_FILE} ${_moc})
				endforeach(_current_MOC_INC)
			endif()
		endif()
		if(NOT _HAS_MOC)
			file(READ ${_abs_FILE} _contents)
			string(REGEX MATCHALL "Q_OBJECT" _match2 "${_contents}")
			if(_match2)
				qt4_make_output_file(${_abs_FILE} moc_ cxx outfile)
				qt4_create_moc_command(${_abs_FILE} ${outfile} "${moc_flags}" "${moc_options}")
				set(${outfiles} ${${outfiles}} ${outfile})
			endif()
		endif()
	endforeach(it)
endmacro(WRAP_CPP)

macro(UPDATE_COMPILER_FLAGS target)
	#get_target_property(COMPILER_FLAGS ${target} COMPILE_FLAGS)
	if(MSVC)
		list(APPEND COMPILER_FLAGS "/W3")
	else()
		list(APPEND COMPILER_FLAGS "-Wall -Wextra -Wnon-virtual-dtor")
	endif()
	set_target_properties(${target} PROPERTIES COMPILE_FLAGS "${COMPILER_FLAGS}")
endmacro()